apiVersion: v1
kind: Namespace
metadata:
  name: mfp-twilio
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mfp-twilio
  namespace: mfp-twilio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mfp-twilio
    spec:
      containers:
      - name: mfp-twilio
        image: jabagawee/mfp-twilio
        env:
        - name: SMS_WEBHOOK_PATH
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: sms-webhook-path
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mfp-twilio
  namespace: mfp-twilio
  labels:
    app: mfp-twilio
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: mfp-twilio
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mfp-twilio
  namespace: mfp-twilio
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - mfp-twilio.doombagoomba.com
    secretName: mfp-twilio-tls
  rules:
  - host: mfp-twilio.doombagoomba.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mfp-twilio
          servicePort: 80
